spring.application.name=subscriptionManagementBackend
server.port=1234

#windsurf.logger@gmail.com
spring.datasource.url=jdbc:postgresql://ep-morning-dawn-a1z18fkr-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8mJlFgCSRQ7G
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.rohan=Debug
logging.file.name=logs/app.log

#redis 
spring.data.redis.host=localhost
spring.data.redis.port=6379

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=techsearch.0101@gmail.com
spring.mail.password=encu dvla mshu daug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true